name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Set the JDK version required by your project
          distribution: 'corretto'  # AWS Corretto distributions
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew bootJar